<#ftl strip_whitespace=true>
<#assign nextId=0 />

<#macro button name type="link" attrs...><#if type=="button"><button name="${name?html}"<@_attributes attrs/>><#nested /></button><#else><a role="button" name="${name?html}" tabindex="0"<@_attributes attrs/>><#nested /></a></#if></#macro>
<#macro label for="" required=false attrs...><#local body><#nested /></#local><#if body?has_content><label<#if for?has_content> for="${for?html}"</#if><@_attributes items=attrs excludes=["for","required"]/>>${body}<#if required?string == "true"><em>*</em></#if></label></#if></#macro>
<#macro checkbox name attrs...><#local is_checked=(attrs["checked"]!false)?string?matches("(true|checked)", "i")/><@label required=attrs["required"]><input type="checkbox" name="${name?html}"<#if is_checked> checked="checked"</#if><@_attributes items=attrs excludes=["type","required","checked"]/>/><#nested /></@label></#macro>
<#macro radio name attrs...><#local is_checked=(attrs["checked"]!false)?string?matches("(true|checked)", "i")/><@label required=attrs["required"]><input type="radio" name="${name?html}"<#if is_checked> checked="checked"</#if><@_attributes items=attrs excludes=["type","required","checked"]/>/><#nested /></@label></#macro>
<#macro input name attrs...><#local id=attrs["id"]!_nextId()/><#local type=attrs["type"]!"text"/><#if type=="submit"><#local label><#nested /></#local><input type="${type?html}" name="${name?html}" id="${id}" value="${label}"<@_attributes items=attrs excludes=["id","type","required"]/>/><#else><@label for=id required=attrs["required"]><#nested /></@label><input type="${type?html}" name="${name?html}" id="${id}"<@_attributes items=attrs excludes=["id","type","required"]/>/></#if></#macro>
<#macro select name items selected="" attrs...><#local id=attrs["id"]!_nextId()/><#local body><#nested /></#local><#local options><#if items?is_hash_ex><#list items?keys as key><option value="${key?html}"<#if selected?? && selected==key> selected="selected"</#if>>${items[key]}</option></#list><#else><#list items as item><option value="${item?html}"<#if selected?? && selected==item> selected="selected"</#if>>${item}</option></#list></#if></#local><#if body?has_content><@label for=id required=attrs["required"]>${body}</@label></#if><select name="${name?html}" id="${id}"<@_attributes items=attrs excludes=['id','required']/>>${options}</select></#macro>
<#macro datagrid name columns=[] height="310px" attrs...><#if height?has_content><div style="height:${height?html}"></#if><table role="grid" aria-label="${name?html}"<@_attributes attrs/>><#if columns?size != 0><thead><tr><#list columns as column><th><#nested column/></th></#list></tr></thead></#if></table><#if height?has_content></div></#if></#macro>
<#macro datalist name items attrs...>
    <#if items?size != 0>
        <ul role="listbox" aria-label="${name?html}" style="height:310px;"<@_attributes items=attrs excludes=["name"]/>>
            <#if items?is_hash_ex><#list items?keys as key><li value="${items[key]?html}">${key}</li></#list>
            <#else><#list items as item><li value="${item?html}">${item}</li></#list>
            </#if>
        </ul>
    <#else><div role="listbox" aria-label="${name?html}" style="height:310px;"<@_attributes items=attrs excludes=["name"]/>></div></#if>
</#macro>
<#macro fields name title="" description="" attrs...><fieldset name="${name?html}"<@_attributes attrs/>><#if description?has_content><legend class="hidden-label"><#if title?has_content>${title}<#else>${description}</#if></legend></#if><@fields_title title, description/><#nested /></fieldset></#macro>
<#macro fields_title title description=""><#if description?length != 0><h6>${title}<span>${description}</span></h6><#elseif title?length != 0><legend>${title}</legend></#if></#macro>
<#macro dialog id escapeAttrs=true attrs...><div id="${id?html}" role="dialog" class="dialog" aria-hidden="true"<@_attributes escapeXml=escapeAttrs items=attrs/>><#nested /></div></#macro>

<#macro dn name maxlength=255 required=true size="" attrs...><#local id=attrs["id"]!_nextId()/><#if maxlength?is_number><#local attrs=attrs + {'maxlength': maxlength?c, 'size': (size!)} /><#else><#local attrs=attrs + {'maxlength': maxlength, 'size': (size!)} /></#if><@label for=id required=required><#nested /></@label><input type="text" name="${name?html}" id="${id}"<@_attributes items=attrs excludes=["id","type"]/>/></#macro>
<#macro username name maxlength=50 required=false size="" attrs...><#local id=attrs["id"]!_nextId()/><#if maxlength?is_number><#local attrs=attrs + {'maxlength': maxlength?c, 'size': (size!)} /><#else><#local attrs=attrs + {'maxlength': maxlength, 'size': (size!)} /></#if><@label for=id required=required><#nested /></@label><input type="text" name="${name?html}" id="${id}"<@_attributes items=attrs excludes=["id","type"]/>/></#macro>
<#macro password name maxlength=255 required=false size="" attrs...><#local id=attrs["id"]!_nextId()/><#if maxlength?is_number><#local attrs=attrs + {'maxlength': maxlength?c, 'size': (size!)} /><#else><#local attrs=attrs + {'maxlength': maxlength, 'size': (size!)} /></#if><@label for=id required=required><#nested /></@label><input type="password" name="${name?html}" id="${id}" autocomplete="off"<@_attributes items=attrs excludes=["id","type","autocomplete"]/>/></#macro>
<#macro url name maxlength=2048 required=false size="" attrs...><#local id=attrs["id"]!_nextId()/><#if maxlength?is_number><#local attrs=attrs + {'maxlength': maxlength?c, 'size': (size!)} /><#else><#local attrs=attrs + {'maxlength': maxlength, 'size': (size!)} /></#if><@label for=id required=required><#nested /></@label><input type="url" name="${name?html}" id="${id}"<@_attributes items=attrs excludes=["id","type"]/>/></#macro>
<#macro path name maxlength=2048 required=false size="" attrs...><#local id=attrs["id"]!_nextId()/><#if maxlength?is_number><#local attrs=attrs + {'maxlength': maxlength?c, 'size': (size!)} /><#else><#local attrs=attrs + {'maxlength': maxlength, 'size': (size!)} /></#if><@label for=id required=required><#nested /></@label><input type="text" name="${name?html}" id="${id}"<@_attributes items=attrs excludes=["id","type"]/>/></#macro>
<#macro host name maxlength=255 required=false size="" attrs...><#local id=attrs["id"]!_nextId()/><#if maxlength?is_number><#local attrs=attrs + {'maxlength': maxlength?c, 'size': (size!)} /><#else><#local attrs=attrs + {'maxlength': maxlength, 'size': (size!)} /></#if><@label for=id required=required><#nested /></@label><input type="text" name="${name?html}" id="${id}"<@_attributes items=attrs excludes=["id","type"]/>/></#macro>
<#macro port name maxlength=5 required=false size="10" attrs...><#local id=attrs["id"]!_nextId()/><#if maxlength?is_number><#local attrs=attrs + {'maxlength': maxlength?c, 'size': (size!)} /><#else><#local attrs=attrs + {'maxlength': maxlength, 'size': (size!)} /></#if><@label for=id required=required><#nested /></@label><input type="text" <#--type="number" -->name="${name?html}" id="${id}" min="0" max="65535"<@_attributes items=attrs excludes=["id","type","min","max"]/>/></#macro>
<#macro email name maxlength=255 required=false size="" attrs...><#local id=attrs["id"]!_nextId()/><#if maxlength?is_number><#local attrs=attrs + {'maxlength': maxlength?c, 'size': (size!)} /><#else><#local attrs=attrs + {'maxlength': maxlength, 'size': (size!)} /></#if><@label for=id required=required><#nested /></@label><input type="text" <#--type="email" -->name="${name?html}" id="${id}"<@_attributes items=attrs excludes=["id","type"]/>/></#macro>
<#macro number name maxlength=19 required=false size="" attrs...><#local id=attrs["id"]!_nextId()/><#if maxlength?is_number><#local attrs=attrs + {'maxlength': maxlength?c, 'size': (size!)} /><#else><#local attrs=attrs + {'maxlength': maxlength, 'size': (size!)} /></#if><@label for=id required=required><#nested /></@label><input type="text" <#--type="number" -->name="${name?html}" id="${id}"<@_attributes items=attrs excludes=["id","type"]/>/></#macro>
<#macro text name maxlength=4096 required=false size="" attrs...><#local id=attrs["id"]!_nextId()/><#if maxlength?is_number><#local attrs=attrs + {'maxlength': maxlength?c, 'size': (size!)} /><#else><#local attrs=attrs + {'maxlength': maxlength, 'size': (size!)} /></#if><@label for=id required=required><#nested /></@label><input type="text" name="${name?html}" id="${id}"<@_attributes items=attrs excludes=["id","type"]/>/></#macro>
<#macro memo name attrs...><#local id=attrs["id"]!_nextId()/><@label for=id required=attrs["required"]><#nested /></@label><textarea name="${name?html}" id="${id}"<@_attributes items=attrs excludes=["id","required","value"]/>>${attrs["value"]!""}</textarea></#macro>
<#macro _attributes items escapeXml=true excludes=[]><#if items?is_hash><#list items?keys as key><#if !excludes?seq_contains(key) && items[key]?has_content> ${key?replace("([a-z])([A-Z])", "$1-$2", "r")?lower_case}<#if escapeXml>="${items[key]?html}"<#else>="${items[key]}"</#if></#if></#list></#if></#macro>
<#function _nextId><#local id=nextId + 1 /><#assign nextId=id /><#return "_${id?c}" /></#function>