/* Copyright © 2009-2024. Redwood Software Inc. All rights reserved. */
jscape.Application=Class.extend({modules:null,started:null,current:null,ready:null,initialize:function(){this.modules={};this.started=[];this.forceStart=[];this.ready=false;$.parser.auto=false;$(window).on("beforeunload",$.proxy(this._onBeforeUnload,this));$(window).on("unload",$.proxy(this._destroy,this));$(document).on("broadcast",$.proxy(this.onBroadcast,this));$(document).on("changelicense",$.proxy(this._onChange$License,this));},register:function(id,module,forceStart){if(!this.modules.hasOwnProperty(id)){this.modules[id]=[];}
this.modules[id].push(module);if(!!forceStart){this.forceStart.push(id);}
return module;},start:function(){var args=$.makeArray(arguments);$(document).ready($.proxy(function(){this._launch.apply(this,args);args=null;},this));},onReady:function(){for(var i=0,len=this.forceStart.length;i<len;++i){this._forceStartModule(this.forceStart[i]);}},onBroadcast:function(e,message,success){if(!message||!message.trim().length){return;}
var top=20+document.body.scrollTop+document.documentElement.scrollTop;if(success===false){$.messager.show({msg:message,noheader:true,height:"auto",showType:"fade",showSpeed:200,border:"thin",style:{top:top,right:"",bottom:"","border-color":"#FFA8A8"}}).window("body").css({"background-color":"#FFF3F3","padding-bottom":"1em","text-align":"center"});}else{var last=$("body>.messager-tip").last();$.messager.tip({msg:message,border:"thin",showSpeed:200,closeAnimation:"fade",closeDuration:600,top:last.length?top+parseInt(last.css("top"))+last._outerHeight():top}).window("body").css("background-color","#C1F0C1");}},onMenuItemSelected:function(item){if(item&&item.id){this._onClick$MenuItem(item.id);}},onBeforeSelectModule:function(id){return this.modules.hasOwnProperty(id);},onSelectModule:function(id){if(!this.modules.hasOwnProperty(id)){return false;}
if(!this.ready){this.forceStart.push(id);return true;}
var previous=this.current;this.current=id;var items=this.modules[id];if(previous!=this.current){if(this.modules.hasOwnProperty(previous)){$.each(this.modules[previous],function(_,module){module.onPause();});}
if($.inArray(id,this.started)==-1){$.each(items,$.proxy(function(_,module){module.onStart();this.started.push(id);},this));}
$.each(items,function(_,module){module.onResume();});}else{$.each(items,function(_,module){module.onRefresh();});}
return true;},currentModuleId:function(){return this.current;},_onChange$License:function(){var current=this.current;$.each(this.modules,$.proxy(function(id){this._forceStopModule(id);},this));for(var i=0,len=this.forceStart.length;i<len;++i){this._forceStartModule(this.forceStart[i]);}
$.each(this.modules,$.proxy(function(id){if(current==id){this._forceStartModule(id);return false;}},this));},_forceStartModule:function(id){this.onSelectModule(id);},_forceStopModule:function(id){if(this.modules.hasOwnProperty(id)){var index=$.inArray(id,this.started);if(index!=-1){var items=this.modules[id];$.each(items,function(_,module){module.onPause();module.onStop();});this.started.splice(index,1);if(id==this.current){this.current=null;}}}},_launch:function(){var args=$.makeArray(arguments);this._parseLayout().then($.proxy(function(){var d=$.Deferred();try{this._createView();$.each(this.modules,function(id,items){$.each(items,function(_,module){module.onCreate.apply(module,args);});});args=null;d.resolve();}catch(e){d.reject(e);}
return d.promise();},this)).done($.proxy(function(){this.ready=true;this.onReady();},this)).fail(function(e){throw"Error starting application: "+e;});},_createView:function(){this.menu=new jscape.Menu($("#menubar").add($("#supportbar")).add($("#userbar")));this.menu.bind($.proxy(this.onMenuItemSelected,this),"application");},_parseLayout:function(){var d=$.Deferred();var p=d.promise();var h=$.parser.onComplete;$.parser.onComplete=function(){$.parser.onComplete=h;d.resolve();d=p=h=null;};setTimeout(function(){$.parser.parse(document);},0);return p;},_onClick$MenuItem:function(id){if("menu-logout"==id){jscape.API.logout();}else{$(document).triggerHandler("selectmenu",[id]);}},_onBeforeUnload:function(e){window.originalEvent=e;var started=[].concat(this.started);$.each(this.modules,function(id,items){if($.inArray(id,started)!=-1){$.each(items,function(_,module){module.onPause.call(module);});}});window.originalEvent=null;return e.returnValue||undefined;},_destroy:function(){$(document).off("broadcast");$(window).off("unload");var started=this.started;for(var id in this.modules){if(this.modules.hasOwnProperty(id)){if($.inArray(id,started)!=-1){$.each(this.modules[id],function(_,module){module.onStop.call(module);});}}}
this.started=[];this.modules=null;}});jscape.ApplicationModule=Class.extend({initialize:function(){},onCreate:function(app){},onStart:function(){},onStop:function(){},onPause:function(){},onResume:function(){},onRefresh:function(){},_showConfirmApply:function(){if(window.originalEvent&&window.originalEvent.type==="beforeunload"){window.originalEvent.returnValue=window.R.string.APPLICATION_CONFIRM_LEAVE;return $.Deferred().reject().promise();}
var deferred=$.Deferred();var promise=deferred.promise();var dlg=$.messager.confirm({title:window.R.string.APPLICATION_TITLE,msg:window.R.string.APPLICATION_CONFIRM_APPLY,closable:false,buttons:[{text:window.R.string.DIALOG_BUTTON_APPLY,onClick:function(){dlg.dialog("close");deferred.resolve(true);dlg=deferred=null;}},{text:window.R.string.DIALOG_BUTTON_DISCARD,onClick:function(){dlg.dialog("close");deferred.reject();dlg=deferred=null;}}]});return promise;},_confirmAndApply:function(controllers){if(arguments.length==1&&!$.isArray(controllers)){controllers=[controllers];}
if(controllers.length==0){return;}
return this._showConfirmApply().done(function(){for(var i=0;i<controllers.length;i++){if(typeof controllers[i].onApply=="function"){controllers[i].onApply();}}}).fail(function(){for(var i=0;i<controllers.length;i++){if(typeof controllers[i].onDiscard=="function"){controllers[i].onDiscard();}}});}});jscape.DashboardView=Class.extend({initialize:function(modules){$("body").css("overflow","hidden");this.throbber=$("#throbber").show();this.viewport=$("#viewpane").layout({fit:true,border:false,width:"100%",height:"100%"});this.viewport.css("visibility","hidden");this.lastLoginDate=$("#last-login");this.modules=$(modules);},show:function(listener){this.listener=listener||jscape.DashboardView.LISTENER;this.throbber.remove();this.throbber=null;this._adjustLoginInfo();this.viewport.css("visibility","visible");$("body").css("overflow","");},selectTab:function(id){this._selectTab(id,this.modules);},_adjustLoginInfo:function(){var t=this.lastLoginDate;var ts=parseInt(t.data("timestamp"));if(!isNaN(ts)){t.text(new Date(ts).toLocaleString(t.attr("lang")));}
t.show();},_initSidemenu:function(sidemenu){var data=sidemenu.children("ul").children("li").map(function(){var t=$(this).children("div");var children=$(this).children("ul").find("li>a").map(function(){return $.extend({text:$(this).text(),collapsed:false},$.parser.parseOptions(this));}).get();return $.extend({text:t.text()},$.parser.parseOptions(t[0]),{children:children});}).get();sidemenu.sidemenu({data:data,multiple:true,collapsed:false,animate:false,border:false,width:"100%",onSelect:$.proxy(this._onSelect$SideMenu,this)});var p=sidemenu.closest(".layout-body.panel-body");p.panel("options").onResize=function(){sidemenu.sidemenu("resize",{width:"100%"});};return sidemenu;},_selectSidemenuItem:function(sidemenu,item){var acc=sidemenu.find(".accordion");acc.accordion("select",item);var p=acc.accordion("getSelected");if(p!=null){var tree=p.find(".sidemenu-tree");var node=tree.tree("getRoot");node&&tree.tree("select",node.target);}},_selectTab:function(id,parent){var candidate=$("#"+id);if(candidate.length==0){return false;}
candidate.parents(".tabs-container").each($.proxy(function(_,elem){var tabs=$(elem);var tabIndex=-1;$.each(tabs.tabs("tabs"),function(i,target){if(target.is(candidate)){tabIndex=i;return false;}
return true;});if(tabIndex!=-1){tabs.tabs("select",tabIndex);}},this));},_onSelect$SideMenu:function(item){},_onBeforeSelect$Module:function(id){return true;},_onSelect$Module:function(title,index){if(!this.listener){return;}
var path=this._findPathSelected(this.modules,title,index);while(path.length){var module=path.pop();if(this.listener.onSelectModule(module)!==false){break;}}},_onSelect$Tab:function(id,tab,parent){this._initSubtabs(tab.children("div[role=tablist]"));if(this._onSelect$Module(id,tab)){if(parent&&parent.data("tabs")){parent.tabs("resize");}}},_initSubtabs:function(el){if(el.length&&el.data("__initialized")!==true){el.data("__initialized",true);el.filter(function(){return $(this).parents("div.dialog").length==0;}).each($.proxy(function(_,t){var tabs=$(t);tabs.tabs({fit:true,border:false,selected:0,onSelect:$.proxy(function(title,index){var tab=tabs.tabs("getTab",index);var opts=tab.panel("options");this._onSelect$Tab.call(this,opts.id||opts.title,tab,tabs);},this)});},this));}
return el;},_updateTabIcon:function(module,iconCls){var path=this._findTab(this.modules,module);if(path&&path.length){this.modules.tabs("update",{tab:path.pop(),type:"header",options:{iconCls:iconCls||null}});}},_findTab:function(parent,id){var path=[];for(var i=0,il=parent!=null?parent.length:0;i<il;++i){if(!!$.data(parent[i],"tabs")){var tabs=$(parent[i]).tabs("tabs");for(var j=0,jl=tabs.length;j<jl;++j){var tab=tabs[j];var opts=tab.panel("options");if(opts.id==id||opts.title==id){path.push(tab);}
path=path.concat(this._findTab(this._subtabs(tab).first(),id));}}}
return path;},_findPathSelected:function(parent,title,index){var path=[];for(var i=0,len=parent!=null?parent.length:0;i<len;++i){if(!$.data(parent[i],"tabs")){continue;}
var selected=$(parent[i]).tabs("getSelected");if(selected==null){continue;}
var opts=selected.panel("options");path.push(opts.id||opts.title);path=path.concat(this._findPathSelected(this._subtabs(selected).first(),title,index));}
return path;},_subtabs:function(parent){if(parent&&parent.length){return parent.children("div[role=tablist]").filter(function(){return $(this).parents("div.dialog").length==0;});}
return null;}});jscape.DashboardView.LISTENER={onSelectModule:$.noop};jscape.Menu=Class.extend({menubar:null,initialize:function(menubar){this.menubar=$(menubar).find("[role=menu]");$.each(this.menubar.filter(":not([aria-hidden])"),$.proxy(function(_,menu){var items=$(menu).find("[role=menuitem]");items.each($.proxy(function(_,item){var btn=$(item).find("[role=button]");if(btn.length){if(/true/i.test(btn.attr("aria-haspopup"))){var submenu=this._createSubmenu($("#"+btn.attr("aria-controls")));btn.menubutton({plain:true,hasDownArrow:true,menu:submenu,showEvent:"click mouseenter"});}else{btn.menubutton({plain:true,hasDownArrow:false});}}},this));},this));},bind:function(fn,namespace){if(typeof fn=="function"){$(document).on("menu.application"+(namespace?"."+namespace:""),function(e,item){return fn(item);});}},unbind:function(namespace){$(document).off("menu.application"+(namespace?"."+namespace:""));},removeMenuItem_:function(menuId,text){var menu=this._findMenu(menuId);if(menu&&menu.length){var el=menu.menu("findItem",text);el&&menu.menu("removeItem",el.target);return true;}
return false;},_onClick$MenuItem:function(data){if(data&&data.id){$(document).triggerHandler("menu.application",data);}},_createSubmenu:function(target){if(target.length){var submenu=$("<div></div>").appendTo("body").attr("id",target.attr("id")||"").menu({noline:true,onClick:$.proxy(function(item){this._onClick$MenuItem({id:item.id});},this)});target.children("[role=menuitem], [role=separator]").each($.proxy(function(_,el){var item=$(el);this._appendMenuItem(item,submenu);item.remove();},this));target.remove();return submenu;}
return null;},_appendMenuItem:function(item,menu){if("separator"===item.attr("role")){menu.menu("appendItem",{separator:true});}else{if(item.hasClass("menu-content")){item.children("div").each($.proxy(function(_,el){var i=$(el);if(i.hasClass("menu-inline")){i.children("div").each($.proxy(function(_,el){this._appendMenuItem($(el),menu);},this));}else{menu.append(el.outerHTML);}},this));}else{var btn=item.find("[role=button]");if(btn.length){btn.each(function(){menu.menu("appendItem",this.href&&this.target!=="_self"?{text:this.outerHTML}:{text:$(this).text(),href:this.href});});}else{var id=item.attr("id")||item.attr("aria-labelledby");menu.menu("appendItem",{id:id,text:item.text()});}}}},_findMenu:function(id){return this.menubar.children("[role=menuitem]").map(function(){var btn=$(this).find("[role=button]");var opts=btn.data("menubutton")?btn.menubutton("options"):{};if(opts.id==id&&opts.menu){return $(opts.menu);}
return null;}).first();}});