{
INTERNAL_ERROR: '<@i18n.message key="Manager.Error.code.INTERNAL_ERROR" />',
BAD_CREDENTIALS: '<@i18n.message key="Manager.Error.code.BAD_CREDENTIALS" />',
NOT_AUTHENTICATED: '<@i18n.message key="Manager.Error.code.NOT_AUTHENTICATED" />',
SESSION_EXPIRED: '<@i18n.message key="Manager.Error.code.SESSION_EXPIRED" />',
DOMAIN_NOT_FOUND: '<@i18n.message key="Manager.Error.code.DOMAIN_NOT_FOUND" />',
ACCESS_DENIED: '<@i18n.message key="Manager.Error.code.ACCESS_DENIED" />',
NO_PERMISSIONS: '<@i18n.message key="Manager.Error.code.NO_PERMISSIONS" />',
SERVICE_EXISTS: '<@i18n.message key="Manager.Error.code.SERVICE_EXISTS" />',
INVALID_FAILOVER_PARAMETERS: '<@i18n.message key="Manager.Error.code.INVALID_FAILOVER_PARAMETERS" />',
INVALID_FAILOVER_CREDENTIALS: '<@i18n.message key="Manager.Error.code.INVALID_FAILOVER_CREDENTIALS" />',
INVALID_EMAIL_SERVER_PARAMETERS: '<@i18n.message key="Manager.Error.code.INVALID_EMAIL_SERVER_PARAMETERS" />',
INVALID_EMAIL_SERVER_CREDENTIALS: '<@i18n.message key="Manager.Error.code.INVALID_EMAIL_SERVER_CREDENTIALS" />',
INVALID_OPERATION_DATA: '${i18n.text("Manager.Error.code.INVALID_OPERATION_DATA")?js_string}',
UNSUPPORTED_DB_DRIVER: '<@i18n.message key="Manager.Error.code.UNSUPPORTED_DB_DRIVER" />',
TEST_INVALID_CREDENTIALS: '<@i18n.message key="Manager.Error.code.TEST_INVALID_CREDENTIALS" />',
TEST_ERROR: '<@i18n.message key="Manager.Error.code.TEST_ERROR" />',
OUT_OF_DATE: '<@i18n.message key="Manager.Error.code.OUT_OF_DATE" />',
IN_USE: '<@i18n.message key="Manager.Error.code.IN_USE" />',
LOGGING_TEST_TITLE: '${i18n.text("Logging.TestDialog.title")?js_string}',
LOGGING_TEST_PASSED_MESSAGE: '${i18n.text("Logging.TestDialog.testPassed")?js_string}',
LOGGING_ERROR_BAD_DIR: '${i18n.text("Logging.Error.badDirectory")?js_string}',
LOGGING_ERROR_BAD_DB_URL: '${i18n.text("Logging.Error.badDbUrl")?js_string}',
LOGGING_ERROR_BAD_DB_USER: '${i18n.text("Logging.Error.badUsername")?js_string}'
}