/* Copyright © 2009-2024. Redwood Software Inc. All rights reserved. */
window.jscape=window.jscape||{};(function(){var fnTest=/xyz/.test(function(){xyz;})?/\b_super\b/:/.*/;var initializing=false;this.Class=function(){};Class.extend=function(prop){var _super=this.prototype;initializing=true;var prototype=new this();initializing=false;for(var name in prop){var overwriting=typeof prop[name]==="function"&&typeof _super[name]==="function"&&fnTest.test(prop[name]);prototype[name]=overwriting?(function(name,fn){return function(){var ref=this._super;this._super=_super[name];var result=fn.apply(this,arguments);this._super=ref;return result;}})(name,prop[name]):prop[name];}
function Class(){if(!initializing&&this.initialize){this.initialize.apply(this,arguments);}}
Class.prototype=prototype;Class.prototype.constructor=Class;Class.extend=arguments.callee;return Class;};})();String.prototype.escapeXml=function(){var entities={"<":"&lt;",">":"&gt;","&":"&amp;",'"':"&quot;"};return this.replace(/[<>&"]/g,function(entry){return entities[entry]});};String.prototype.supplant=function(substitution){return this.replace(/\{([^{}]*)\}/g,function(value,variable){var replacement=substitution[variable];return typeof replacement==="string"||typeof replacement==="number"||typeof replacement==="boolean"?replacement:value;});};jscape.Application=Class.extend({modules:null,started:null,current:null,ready:null,initialize:function(){$.parser.auto=false;this.pageTitle=document.title;this.modules={};this.started=[];this.forceStart=[];this.ready=false;$(window).on("beforeunload",$.proxy(this._onBeforeUnload,this));$(window).on("unload",$.proxy(this._destroy,this));$(document).on("broadcast",$.proxy(this.onBroadcast,this));},register:function(id,module,forceStart){if(!this.modules.hasOwnProperty(id)){this.modules[id]=[];}
this.modules[id].push(module);if(!!forceStart){this._delayModuleStart(id);}},start:function(){var args=$.makeArray(arguments);$(document).ready($.proxy(function(){this._launch.apply(this,args);args=null;},this));},onReady:function(){var copy=[].concat(this.forceStart);while(copy.length){var module=copy.pop();this._forceStartModule(module.id,module.title);}},onBroadcast:function(e,message,success){if(message&&message.trim().length){$.messager.show({msg:message,escapeXml:true,noheader:true,height:"auto",showType:"fade",showSpeed:200,border:"thin",style:{top:document.body.scrollTop+document.documentElement.scrollTop+20,right:"",bottom:"","border-color":success==false?"#FFA8A8":"#808080"}}).window("body").css({"background-color":success==false?"#FFF3F3":"#C1F0C1","padding-bottom":"1em","text-align":"center"});}},onSelectModule:function(id,pageTitle){if(!this.modules.hasOwnProperty(id)){return false;}
if(!this.ready){this._delayModuleStart(id,pageTitle);return true;}
var previous=this.current;this.current=id;var items=this.modules[id];if(previous!=this.current){if(this.modules.hasOwnProperty(previous)){$.each(this.modules[previous],function(_,module){module.onPause();});}
if($.inArray(id,this.started)==-1){$.each(items,$.proxy(function(_,module){module.onStart();this.started.push(id);},this));}
$.each(items,function(_,module){module.onResume();});this._setWindowTitle(pageTitle);}
return true;},_forceStartModule:function(id,title){this.onSelectModule(id,title);},_forceStopModule:function(id){if(this.modules.hasOwnProperty(id)){var index=$.inArray(id,this.started);if(index!=-1){var items=this.modules[id];$.each(items,function(_,module){module.onPause();module.onStop();});this.started.splice(index,1);if(id==this.current){this.current=null;}}}},_delayModuleStart:function(id,title){var contains=$.grep(this.forceStart,function(m){return m.id===id;}).length>0;if(!contains){this.forceStart.push({id:id,title:title||""});}},_launch:function(){var args=$.makeArray(arguments);this._parseLayout().then($.proxy(function(){var d=$.Deferred();try{this._createView();$.each(this.modules,function(id,items){$.each(items,function(_,module){module.onCreate.apply(module,args);});});args=null;d.resolve();}catch(e){d.reject(e);}
return d.promise();},this)).done($.proxy(function(){this.ready=true;this.onReady();},this)).fail(function(e){throw"Error starting application: "+e;});},_createView:function(){},_parseLayout:function(){var d=$.Deferred();var h=$.parser.onComplete;$.parser.onComplete=function(){$.parser.onComplete=h;d.resolve();h=null;d=null;};setTimeout(function(){$.parser.parse(document);},0);return d.promise();},_onBeforeUnload:function(e){window.originalEvent=e;var started=[].concat(this.started);$.each(this.modules,function(id,items){if($.inArray(id,started)!=-1){$.each(items,function(_,module){module.onPause.call(module);});}});window.originalEvent=null;return e.returnValue||undefined;},_destroy:function(){$(document).off("broadcast");$(window).off("unload");var started=this.started;for(var id in this.modules){if(this.modules.hasOwnProperty(id)){if($.inArray(id,started)!=-1){$.each(this.modules[id],function(_,module){module.onStop.call(module);});}}}
this.started=[];this.modules=null;},_setWindowTitle:function(title){if(!!title){document.title=title+" - "+this.pageTitle;}}});jscape.DashboardView=Class.extend({initialize:function(modules,listener){this.modules=modules;this.listener=listener||jscape.DashboardView.LISTENER;$("body").css("overflow","hidden");this.throbber=$("#throbber").show();this.viewport=$("#viewpane").css("visibility","hidden");this.lastLoginDate=$("#last-login");},show:function(){this.throbber.remove();this.throbber=null;this.viewport.css("visibility","visible");$("body").css("overflow","");this._adjustLoginInfo();},_adjustLoginInfo:function(){var t=this.lastLoginDate;var ts=parseInt(t.data("timestamp"));if(!isNaN(ts)){t.text(new Date(ts).toLocaleString(t.attr("lang")));}
t.show();},_onSelect$Module:function(title,index){if(!this.listener){return;}
var path=this._findPathSelected(this.modules,title,index,0);var titles=$.map(path,function(m){return m.level==0?m.title:null;});while(path.length){var module=path.pop();var pageTitle=titles.length?titles[0]:undefined;if(this.listener.onSelectModule(module.id||module.title,pageTitle)!==false){break;}}},_updateTabIcon:function(module,iconCls){var path=this._findTab(this.modules,module);if(path&&path.length){this.modules.tabs("update",{tab:path.pop(),type:"header",options:{iconCls:iconCls||null}});}},_findTab:function(parent,id){var path=[];for(var j=0,len=parent!=null?parent.length:0;j<len;++j){var tabs=$(parent[j]).tabs("tabs");for(var i=0;i<tabs.length;++i){var tab=tabs[i];var opts=tab.panel("options");if(opts.id==id||opts.title==id){path.push(tab);}
path=path.concat(this._findTab(this._subtabs(tab).first(),id));}}
return path;},_findPathSelected:function(parent,title,index,level){var path=[];for(var j=0,len=parent!=null?parent.length:0;j<len;++j){var tabs=$(parent[j]);if(!tabs.data("tabs")){continue;}
var selected=tabs.tabs("getSelected");if(tabs.tabs("getTabIndex",selected)==-1){continue;}
var opts=selected.panel("options");path.push({id:opts.id,title:opts.title,level:level++});path=path.concat(this._findPathSelected(this._subtabs(selected).first(),title,index,level));}
return path;},_subtabs:function(parent){if(parent&&parent.length){return parent.find("[role=tablist]").filter(function(){return $(this).closest("[role=dialog]").length==0;});}
return null;}});jscape.DashboardView.LISTENER={onSelectModule:$.noop};jscape.ApplicationModule=Class.extend({onCreate:function(){},onStart:function(){},onPause:function(){},onResume:function(){},onStop:function(){}});jscape.InactivityServiceModule=jscape.ApplicationModule.extend({timerId:null,reminderId:null,initialize:function(timeout,gracePeriod){this.timeout=parseInt(timeout)||0;this.gracePeriod=parseInt(gracePeriod)||0;},onStart:function(){if(this.timeout>0){this._startTimer();$(document).ajaxStart($.proxy(this.onResume,this));$(document).on("_activity.user",$.proxy(this.onResume,this));}},onResume:function(){this._startTimer();},onStop:function(){$(document).off(".user");this.timerId&&clearTimeout(this.timerId);this.timerId=null;this.reminderId&&clearInterval(this.reminderId);this.reminderId=null;this.dialog&&this.dialog.destroy();this.dialog=null;},onTimeout:function(){this.dialog=new jscape.InactivityReminderDialog().show(this);this._startReminder(this.dialog);},onReminderTimeout:function(){this.onStop();jscape.API.logout();},onSubmit:function(dialog){clearInterval(this.reminderId);dialog.destroy();this.onResume();},_startTimer:function(){if(this.timerId){clearTimeout(this.timerId);}
this.timerId=setTimeout($.proxy(function(){this.timerId=null;this.onTimeout();},this),this.timeout);},_startReminder:function(dialog){if(this.reminderId){clearInterval(this.reminderId);}
var remainingTime=this.gracePeriod;function _remainder(timeout){dialog.setReminder(Math.round(timeout/1000),Math.round(remainingTime/1000));}
_remainder(this.timeout);this.reminderId=setInterval($.proxy(function(){if(remainingTime>0){_remainder(this.timeout);}else{this.onReminderTimeout();remainingTime=null;}
remainingTime-=1000;},this),1000);}});jscape.InactivityReminderDialog=Class.extend({setReminder:function(timeout,remainTime){if(this.dialog){var button=this.dialog.dialog("options").buttons[0].text;var message=window.R.string.APPLICATION_CONFIRM_ACTIVE.supplant({0:timeout,1:"<b>"+button+"</b>",2:"<b>"+remainTime+"</b>"});var panel=this.dialog.dialog("body");panel.html(panel.html().replace(this.reminder,message));this.reminder=message;}},show:function(listener){this.reminder=window.R.string.APPLICATION_CONFIRM_ACTIVE;this.dialog=$.messager.alert({title:window.R.string.APPLICATION_TITLE,msg:this.reminder,icon:"warning",timeout:0,fn:$.proxy(this._onSubmit,this)});this.listener=listener;return this;},destroy:function(){this.dialog=null;this.listener=null;},_onSubmit:function(){this.listener.onSubmit(this);}});