/* Copyright © 2009-2024. Redwood Software Inc. All rights reserved. */
jscape.ui=jscape.ui||{};jscape.ui.DatagridController=Class.extend({_recordAdded:function(record){this._fireApplySuccess();this._reloadAndSelect(record);},_recordEdited:function(record){this._fireApplySuccess();this._reloadAndSelect(record);},_recordDeleted:function(records){var copy=[].concat(this.view.getRecords());var index=-1;while(records.length){index=$.inArray(records.shift(),copy);copy.splice(index,1);}
if(copy.length){index=Math.min(Math.max(0,index),copy.length-1);this._reloadAndSelect(copy[index]);}else{this._gotoPreviousPage();}},_reloadAndSelect:function(record){this.view.refresh($.proxy(function(){record&&this.view.selectRecord(record);},this));},_gotoPreviousPage:function(){this.view.previousPage($.proxy(function(){var records=this.view.getRecords();records.length&&this.view.selectRecord(records[records.length-1]);},this));},_fireApplySuccess:function(){$(document).triggerHandler("broadcast",[window.R.string.APPLICATION_SUCCESS_APPLY]);}});jscape.ui.DatagridView=Class.extend({refresh:function(callback){this.data.datagrid("reload",callback);},firstPage:function(){this.data.datagrid("gotoPage",{page:1});},previousPage:function(callback){var pageNumber=this.data.datagrid("options").pageNumber;if(pageNumber>1&&this.data.datagrid("getData").total>0){this.data.datagrid("gotoPage",{page:--pageNumber,callback:callback});}else{this.data.datagrid("reload",callback);}},nextPage:function(callback){var opts=this.data.datagrid("options");var total=this.data.datagrid("getData").total;if(opts.pageNumber>0&&total>0&&Math.ceil(total/opts.pageSize)>opts.pageNumber){this.data.datagrid("gotoPage",{page:opts.pageNumber+1,callback:callback});}else{this.data.datagrid("reload",callback);}},getRecords:function(){return this.data.datagrid("getRows");},indexOf:function(value){return this.data.datagrid("getRowIndex",this._valueOf(value));},selectRecord:function(value){var index=this.indexOf(value);if(index!=-1){if(!this.data.datagrid("options").singleSelect){this.data.datagrid("clearSelections");}
this.data.datagrid("selectRow",index);}},_valueOf:function(obj){var idField=this.data.datagrid("options").idField;return obj&&typeof obj=="object"&&idField in obj?obj[idField]:obj;},_pageSelectionFor:function(grid){var opts=grid.datagrid("options");var selection=grid.datagrid("getSelections");if(!opts.pagination||!opts.idField){return selection;}
var pageIds=$.map(grid.datagrid("getRows"),function(row){return row[opts.idField];});return $.grep(selection,function(row){return $.inArray(row[opts.idField],pageIds)!=-1;});},_onRow$ContextMenu:function(e,index,row){e.preventDefault();var grid=(this.data||$(e.target).closest("div.datagrid-view").children(".datagrid-f"));if(grid&&grid.length){grid.datagrid("cancelEdit");if(row&&index>=0){var selection=grid.datagrid("getSelections");if($.inArray(row,selection)===-1){grid.datagrid("unselectAll").datagrid("selectRow",index);}}else{grid.datagrid("unselectAll");}
this._showContextMenu(e,[],index,row);}},_showContextMenu:function(e,entries,index,row){var suffix=""+(1E9*Math.random()>>>0);var items=[];for(var i=0,len=entries.length;i<len;++i){var opts=this._contextMenuItemOptions(entries[i],suffix);if(opts.separator){if(items.length<=0||i>=len-1||items[items.length-1].separator){continue;}
items.push(opts);}
if(opts.handler||opts.submenu){items.push(opts);}}
if(items.length){var menu=$("<div></div>").appendTo($(e.target).closest(".datagrid-body")).menu({onHide:function(){var m=$(this);setTimeout(function(){m.menu("destroy");m=null;},100);}}).off(".grid").on("contextmenu.grid",function(e){e.preventDefault();});this._createContextMenu(menu,items).menu("show",{top:e.pageY||0,left:e.pageX||0});}},_createContextMenu:function(menu,items,parentId){$.each(items,$.proxy(function(_,opts){if(opts.handler||opts.separator){var itemId=parentId!==undefined?parentId:opts.id;var item=menu.menu("findItem",function(mi){return mi.id&&mi.id==itemId});if(parentId&&item&&item.target){menu.menu("appendItem",$.extend(opts,{parent:item.target}));}else{menu.menu("appendItem",opts);}}else if(opts.submenu){var id="_"+(1E9*Math.random()>>>0);menu.menu("appendItem",{id:id,text:opts.text,disabled:!!opts.disabled});this._createContextMenu(menu,opts.submenu,id);}},this));return menu;},_contextMenuItemOptions:function(data,suffix){if("-"===data){return{separator:true};}
if(typeof data==="object"&&data.hasOwnProperty("button")&&data.hasOwnProperty("submenu")){if(data.button.length&&data.submenu.length){var sm=data.submenu;var onClick=sm.menu("options").onClick;var subMenuItems=$.map(sm.children(".menu-item"),function(el){return $.extend({},sm.menu("getItem",el),{handler:function(e){var menu=$(e.target).closest(".menu");menu.length&&onClick.call(menu[0],menu.menu("getItem",this));}});});return $.extend(this._contextMenuItemOptions(data.button),{handler:null,submenu:subMenuItems});}
return{};}
if(data&&data.length&&$.data(data[0],"linkbutton")){var opts=data.linkbutton("options");var text=data.text()||opts.text;var id=text.toLowerCase().replace(/[^\w]/g,"")+(suffix||"");return{id:id,text:text,handler:opts.onClick,disabled:!!opts.disabled};}
return $.isPlainObject(data)?data:{};}});jscape.ui.DefaultDialog=Class.extend({id:null,initialize:function(selector,options){this.dialog=$(selector).clone().attr("id",this.getId());var okButtonId="ok"+this.getIdSuffix();this.dialog.dialog($.extend({height:"auto",modal:true,resizable:true,closable:true,closed:true,buttons:[{text:window.R.string.DIALOG_BUTTON_OK||"OK",id:okButtonId,handler:$.proxy(this._onSubmit,this)},{text:window.R.string.DIALOG_BUTTON_CANCEL||"Cancel",handler:$.proxy(this._onCancel,this)}],onClose:$.proxy(function(){if(!this.closing){this._onCancel();}},this)},options)).show();this.dialog.window("window").attr("tabindex",0).css({outline:"none"}).keydown($.proxy(function(e){if(this.isOnTop()){if(e.keyCode==13){if(!(e.target&&"textarea"==e.target.tagName.toLowerCase())){e.stopPropagation();this._onSubmit();}}else if(e.keyCode==27){e.stopPropagation();this._onCancel();}}},this));this.title=this.dialog.dialog("header").text()||"";this.okButton=this.dialog.siblings(".dialog-button").children("#"+okButtonId);this._adjustChildrenId(this.dialog);},getId:function(){if(this.id==null){this.id=this._nextId();}
return this.id;},getIdSuffix:function(){return"_"+this.getId();},idFor:function(id){return id+this.getIdSuffix();},isOnTop:function(){var zIndexes=$.map(document.getElementsByClassName("window"),function(w){return parseInt($(w).css("z-index"));}).sort();return zIndexes.length&&zIndexes.pop()==parseInt(this.dialog.dialog("window").css("z-index"));},setTitle:function(title){this.dialog.dialog("setTitle",title||"");},show:function(listener){this.listener=listener;this.dialog.dialog("center").dialog("open");if(this.fieldset){this.fieldset.form("validate");this.fieldset.find(":input").filter(":not(:disabled):not(:checkbox)").first().focus();}},hide:function(){if(!this.dialog.dialog("options").closed){this.closing=true;this.dialog.dialog("close");if(this.fieldset){this.fieldset.form("disableValidation");}
this.closing=false;}},destroy:function(){if(this.dialog&&this.dialog.length&&$.data(this.dialog[0],"dialog")){this.dialog.dialog("destroy");this.okButton=null;}},_valid:function(){return this.fieldset?this.fieldset.form("validate"):true;},_onSubmit:function(){if(this._valid()&&this.listener&&this.listener.onSubmit){this.okButton.linkbutton("disable");var p=this.listener.onSubmit(this);if(typeof p==="object"&&typeof p.promise==="function"){p.done($.proxy(this.destroy,this)).fail($.proxy(function(){this.okButton&&this.okButton.linkbutton("enable");},this));}else{this.okButton&&this.okButton.linkbutton("enable");}}},_onCancel:function(){if(this.listener&&this.listener.onCancel){this.listener.onCancel(this);}},_adjustChildrenId:function(parent){function _update(elem,attr,suffix){elem.each(function(){$(this).attr(attr,$(this).attr(attr)+suffix);});}
parent=parent||this.dialog;var suffix=this.getIdSuffix();_update(parent.find("[id]"),"id",suffix);_update(parent.find("label[for]"),"for",suffix);_update(parent.find("[aria-describedby]"),"aria-describedby",suffix);},_nextId:function(prefix){return(prefix||"")+(1E9*Math.random()>>>0);}});jscape.AutoCompleteController=Class.extend({ID:"autocomplete-list",list:null,initialize:function(){this.list=$("#"+this.ID);},start:function(input,suggestions){this.input=input;suggestions=this._formatSuggestions(suggestions);this._create(suggestions).combobox("showPanel").combobox("clear").combobox("textbox").focus();},_formatSuggestions:function(items){return $.map(items||[],function(item){return typeof item=="object"?item.hasOwnProperty("description")?{value:item.value||item.text,text:item.text,title:item.description}:{value:item.value||item.text,text:item.text}:{value:item,text:item};});},_create:function(items){if(this.list==null||this.list.length==0){this.list=$("<select id='"+this.ID+"'></select>");this.list.appendTo(document.body);}
this.list.combobox({data:items,editable:true,hasDownArrow:false,width:250,delay:0,filter:function(q,row){return row[$(this).combobox("options").valueField].toLocaleLowerCase().indexOf(q.toLocaleLowerCase())>=0;},formatter:function(row){var text=(""+row.text).escapeXml();return row.title?'<span title="{tip}">{text}</span>'.supplant({tip:row.title.escapeXml(),text:text}):text},onHidePanel:$.proxy(this._onHide,this)});this._align();return this.list;},_align:function(){var offset=this.input.offset();var left=Math.max(0,Math.min(offset.left,$(window).outerWidth()+$(document).scrollLeft()-this.list.outerWidth()-5));var top=Math.max(0,Math.min(offset.top+this.input.outerHeight(),$(window).outerHeight()+$(document).scrollTop()-this.list.outerHeight()-5));this.list.combobox("textbox").parent().css({position:"absolute",left:left,top:top,zIndex:$.fn.window.defaults.zIndex++});},_onHide:function(){var value=this.list.combobox("getValue");if(value){this._insertText(this.input,value);}
this.input.focus();this.list.combobox("destroy");this.input=null;this.list=null;},_insertText:function(input,text){var value=input.val();var tb=input.parent().prev();var len=text.length;if(tb.data("textbox")){var range=tb.textbox("getSelectionRange");tb.textbox("initValue",value.substring(0,range.start)+text+value.substring(range.end)).textbox("setSelectionRange",{start:range.start,end:range.start+text.length});input.blur();}else{var caret=this._caret(input);input.focus();input.val(value.substring(0,caret.start)+text+value.substring(caret.end));input.blur();input[0].selectionStart=input[0].selectionEnd=input[0].selectionStart+text.length;input.change();}},_caret:function(input){var caret={start:0,end:0};if(document.selection&&document.selection.createRange){var r1,r2,selection=document.selection;if("textarea"==input[0].tagName.toLowerCase()){r1=selection.createRange();r2=r1.duplicate();r2.moveToElementText(input[0]);r2.setEndPoint("EndToEnd",r1);caret.start=r2.text.length-r1.text.length;caret.end=caret.start+r1.text.length;}else{var value=input.val();r1=selection.createRange().duplicate();r2=selection.createRange().duplicate();r1.moveEnd("character",value.length);r2.moveStart("character",-value.length);caret.start=r1.text.length?value.lastIndexOf(r1.text):value.length;caret.end=r2.text.length;}}else{caret.start=input[0].selectionStart;caret.end=input[0].selectionEnd;}
return caret;}});jscape.VariableController=jscape.AutoCompleteController.extend({_insertText:function(input,value){if(this._nestedContext(input)){this._super(input,value);}else{this._super(input,"%"+value+"%");}},_nestedContext:function(input){var text=input.val().substring(0,this._caret(input).start);var count=0;for(var i=0;i<text.length;i++){if(text.charAt(i)==="%"){count++;}}
return count%2!=0;}});jscape.CopyToClipboardController=Class.extend({start:function(text,target,message,position){var d=$.Deferred();if(text&&this._copyText(text)){d.resolve();}else{d.reject();}
return d.promise().done($.proxy(this._showTooltip,this,target,message,position));},_copyText:function(text){var $el=$("<textarea id='__"+(1E9*Math.random()>>>0)+"'></textarea>").css({position:"absolute",top:0,left:"-100000px"}).appendTo("body");try{$el[0].textContent=text;$el[0].focus();$el[0].setSelectionRange(0,$el.val().length);return document.execCommand("copy");}catch(e){return false;}finally{$el[0].textContent="";$el.remove();}},_showTooltip:function(target,message,position){message=message||"Copied";if(target&&target.length){target.tooltip({content:message,position:position||"right",showEvent:"none",showDelay:0,hideEvent:"none",hideDelay:2000,onShow:function(){$(this).tooltip("hide");},onHide:function(){$(this).tooltip("destroy");}}).tooltip("show");}else{$(document).triggerHandler("broadcast",[message]);}}});jscape.ConfirmDialog={};jscape.ConfirmDialog.confirm=function(title,message,escape){var deferred=$.Deferred();var dlg=$.messager.confirm({title:title,msg:message,escapeXml:escape!==false,fn:function(confirmed){if(confirmed){deferred.resolve(confirmed);}else{deferred.reject();}
deferred=null;},onClose:function(){var opts=$(this).dialog("options");!opts.__handled&&opts.fn(false);}});dlg.next(".messager-button").find(".l-btn").each(function(){var opts=$(this).linkbutton("options");var onClick=opts.onClick;opts.onClick=function(){dlg.dialog("options").__handled=true;onClick&&onClick.apply(this,arguments);}});return deferred.promise();};jscape.Validator=Class.extend({rule:function(key,validator,message){var rules={};rules[key]={validator:validator,message:message||"Please provide valid data."};$.extend($.fn.validatebox.defaults.rules,rules);},ruleMessage:function(key,message){var rule=$.fn.validatebox.defaults.rules[key];if(rule){if(arguments.length==1){return rule.message;}
rule.message=message;}},nonEmptyRule:function(key,message){this.rule(key,function(value){return value.trim().length!=0;},message);},isSatisfied:function(key,value){var rule=$.fn.validatebox.defaults.rules[key];if(rule&&$.isFunction(rule.validator)){var params=arguments.length>1?Array.prototype.slice.call(arguments,2):[];return rule.validator.call(rule.validator,value,params);}
return true;},validateTabs:function(tabs){var fields=tabs.find(".validatebox-text:not(:disabled)");for(var i=0;i<fields.length;i++){var field=$(fields[i]);if(!field.validatebox("isValid")){this._navigateFrom(field);field.focus();return false;}}
return true;},_navigateFrom:function(source){source.parents(".tabs-container").each($.proxy(function(_,elem){var tabs=$(elem);var tabIndex=-1;$.each(tabs.tabs("tabs"),function(i,target){if(target.has(source).length!=0){tabIndex=i;return false;}
return true;});if(tabIndex!=-1){tabs.tabs("select",tabIndex);}
if(this.tabs!=tabs){this._navigateFrom(tabs);}},this));}});jscape.SizeFormat=Class.extend({SIZE:{BYTE:{factor:1,unit:"byte(s)"},KB:{factor:1024,unit:"KiB"},MB:{factor:1024*1024,unit:"MiB"},GB:{factor:1024*1024*1024,unit:"GiB"},TB:{factor:1024*1024*1024*1024,unit:"TiB"}},format:function(value){var size;if(value<this.SIZE.KB.factor){size=this.SIZE.BYTE;}else if(this.SIZE.KB.factor<=value&&value<this.SIZE.MB.factor){size=this.SIZE.KB;}else if(this.SIZE.MB.factor<=value&&value<this.SIZE.GB.factor){size=this.SIZE.MB;}else if(this.SIZE.GB.factor<=value&&value<this.SIZE.TB.factor){size=this.SIZE.GB;}else{size=this.SIZE.TB;}
var digits=size==this.SIZE.BYTE?0:2;return(value/size.factor).toFixed(digits)+" "+size.unit;}});jscape.SizeFormat.format=function(value){return new jscape.SizeFormat().format(value);};jscape.DateFormat=Class.extend({initialize:function(pattern){this.pattern=pattern||"{hh}:{mm}:{ss} {MM}-{dd}-{yy}";},format:function(date){var year=date.getFullYear();var month=date.getMonth()+1;var day=date.getDate();var hours=date.getHours();var minutes=date.getMinutes();var seconds=date.getSeconds();var millis=date.getMilliseconds();return this.pattern.supplant({d:day,dd:this._leadingZero(day),M:month,MM:this._leadingZero(month),y:year,yy:this._leadingZero(year),h:hours,hh:this._leadingZero(hours),m:minutes,mm:this._leadingZero(minutes),s:seconds,ss:this._leadingZero(seconds),S:millis,SS:this._leadingZero(millis)});},_leadingZero:function(value){return(value<10?"0":"")+value;}});jscape.DateFormat.format=function(value,pattern){return value?new jscape.DateFormat(pattern).format(typeof value==="number"?new Date(value):value):"";};jscape.Page=Class.extend({initialize:function(a,b,c){this.records=$.isArray(a)?a:[];this.recordIndex=parseInt(b)||0;this.totalRecords=parseInt(c)||this.records.length;}});jscape.Page.fromJSON=function(data,recordsProvider){return $.isPlainObject(data)?new jscape.Page($.map(data.records||[],recordsProvider),data.recordIndex,data.totalRecords):new jscape.Page($.map($.isArray(data)?data:[],recordsProvider));};jscape.Page.requestParameters=function(params){function parametrize(value){return value?value.replace(/([a-z])([A-Z])/g,"$1_$2").toUpperCase():value;}
var startIndex,count,query;if($.isPlainObject(params)){startIndex=params.page?(params.page-1)*params.rows:null;count=params.rows||null;query=$.extend({},params);delete query.page;delete query.rows;query.sort=parametrize(query.sort);query.order=parametrize(query.order);query.field=parametrize(query.field);}
return{startIndex:startIndex,count:count,query:query};};jscape.Page.datagridFormatter=function(){return function(page){return $.isArray(page)?{total:page.length,rows:page}:{total:page.totalRecords,rows:page.records};}};Object._equals=function(o1,o2){if(o1===o2){return true;}
if(o1===null||$.type(o1)!==$.type(o2)){return false;}
if(o1!==o1&&o2!==o2){return true;}
var type=$.type(o1);if(type==="date"){return o1.getTime()==o2.getTime();}else if(type==="regexp"){return o1.toString()==o2.toString();}else if(type==="array"){if(o1.length!=o2.length){return false;}
for(var i=0;i<o1.length;i++){if(!Object._equals(o1[i],o2[i])){return false;}}
return true;}else if(type==="object"){var prop;for(prop in o1){if(o1.hasOwnProperty(prop)&&(o2[prop]===undefined||!Object._equals(o1[prop],o2[prop]))){return false;}}
for(prop in o2){if(o2.hasOwnProperty(prop)&&o1[prop]===undefined){return false;}}
return true;}
return false;};